version: "3.8"
services:
  production:
    container_name: docker-motorez-front
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64/v8
    restart: unless-stopped
    ports:
      - "3007:3000"
